# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18de6a654fe64802a8088bbc8f8c9ac205166060345530cbc33d0d7a4a883eab5db87da0f3e36334370bfe621e6a7fe1b4e49dd5481c48da73b4332d75ba952

test:
  secret_key_base: f90c8b522fc7b72133f1b8fbdc71ad1b496cc5d5115528d304045ecf3cfd9ac03b0c2d86ecd0e4738b72052889d488821bfc186d38c7988122eaa203abb1abb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
